#!/usr/bin/env node
// Generates src/generated/{enums,types,operations}.ts from the vendored OpenAPI
// specs in spec/. Zero dependencies. Output is committed — re-run this after
// scripts/fetch-spec.mjs and review the diff.
//
// DO NOT hand-edit anything under src/generated/.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const root = new URL('..', import.meta.url)
const read = (p) => JSON.parse(readFileSync(new URL(p, root), 'utf8'))
const v1 = read('spec/public_v1.json')
const v2 = read('spec/public_v2.json')

const BANNER = `// AUTO-GENERATED by scripts/generate.mjs — DO NOT EDIT.
// Source: spec/public_v1.json, spec/public_v2.json (SEF public OpenAPI).
`

// ---------------------------------------------------------------- utilities

const refName = (ref) => ref.split('/').pop()
const isIdent = (s) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s)
const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1)

/** Escape a string for a TS single-quoted literal. */
const lit = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

/**
 * Merge the two specs' schema maps. v2 redefines a handful of names
 * (e.g. IndividualVatRecordDto) with a different shape, so v2 schemas are
 * suffixed with `V2` rather than silently overwriting the v1 definition.
 */
function collectSchemas() {
  const out = new Map()
  for (const [name, schema] of Object.entries(v1.components?.schemas ?? {})) {
    out.set(name, { name, schema, version: 'v1' })
  }
  const v2Renames = new Map()
  for (const [name, schema] of Object.entries(v2.components?.schemas ?? {})) {
    const existing = out.get(name)
    if (!existing) {
      out.set(name, { name, schema, version: 'v2' })
      continue
    }
    if (JSON.stringify(existing.schema) === JSON.stringify(schema)) continue
    const alias = `${name}V2`
    v2Renames.set(name, alias)
    out.set(alias, { name: alias, schema, version: 'v2' })
  }
  return { schemas: out, v2Renames }
}

const { schemas, v2Renames } = collectSchemas()

/** Resolve a $ref to the emitted type name, honouring v2 renames. */
function resolveRef(ref, version) {
  const raw = refName(ref)
  const name = version === 'v2' && v2Renames.has(raw) ? v2Renames.get(raw) : raw
  // Enums are emitted PascalCase (the spec has a couple of camelCase enum
  // names, e.g. eSortColumn), so refs to them must be renamed to match.
  const target = schemas.get(name)
  if (target && Array.isArray(target.schema.enum)) return pascal(name)
  return name
}

/** Map an OpenAPI schema node to a TypeScript type expression. */
function tsType(schema, version) {
  if (!schema) return 'unknown'
  if (schema.$ref) return resolveRef(schema.$ref, version)
  if (schema.enum) return schema.enum.map((v) => lit(v)).join(' | ')
  switch (schema.type) {
    case 'array':
      return `${tsType(schema.items, version)}[]`
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'string':
      return 'string'
    case 'object':
      if (schema.additionalProperties && schema.additionalProperties !== true) {
        return `Record<string, ${tsType(schema.additionalProperties, version)}>`
      }
      return 'Record<string, unknown>'
    default:
      return 'unknown'
  }
}

// -------------------------------------------------------------------- enums

const enumEntries = []
for (const { name, schema } of schemas.values()) {
  if (!Array.isArray(schema.enum)) continue
  enumEntries.push({ name, values: schema.enum, description: schema.description })
}
enumEntries.sort((a, b) => a.name.localeCompare(b.name))

function emitEnums() {
  const parts = [BANNER]
  for (const { name, values, description } of enumEntries) {
    const typeName = pascal(name)
    if (description) parts.push(`/** ${description.replace(/\*\//g, '')} */`)
    parts.push(`export const ${typeName} = {`)
    for (const v of values) {
      const key = isIdent(v) ? v : lit(v)
      parts.push(`  ${key}: ${lit(v)},`)
    }
    parts.push(`} as const`)
    parts.push(
      `export type ${typeName} = (typeof ${typeName})[keyof typeof ${typeName}]`,
      '',
    )
  }
  return parts.join('\n')
}

// -------------------------------------------------------------------- types

const enumNames = new Set(enumEntries.map((e) => pascal(e.name)))

function emitTypes() {
  const parts = [BANNER]
  const used = [...enumNames].sort()
  parts.push(`import type {\n${used.map((n) => `  ${n},`).join('\n')}\n} from './enums.ts'`)
  parts.push(`export type {\n${used.map((n) => `  ${n},`).join('\n')}\n}`)
  parts.push('')

  const objects = [...schemas.values()]
    .filter(({ schema }) => !schema.enum)
    .sort((a, b) => a.name.localeCompare(b.name))

  for (const { name, schema, version } of objects) {
    if (schema.type && schema.type !== 'object') {
      parts.push(`export type ${name} = ${tsType(schema, version)}`, '')
      continue
    }
    const props = schema.properties ?? {}
    const required = new Set(schema.required ?? [])
    parts.push(`export interface ${name} {`)
    for (const [prop, def] of Object.entries(props)) {
      // Swashbuckle marks C# reference types that may be null as
      // `nullable: true`. Treat those as optional-and-nullable and everything
      // else as always present — that mirrors the server's actual behaviour
      // far better than making all 501 properties optional.
      const nullable = def.nullable === true
      const optional = nullable && !required.has(prop)
      const key = isIdent(prop) ? prop : lit(prop)
      let type = tsType(def, version)
      if (nullable) type += ' | null'
      if (def.description) parts.push(`  /** ${def.description.replace(/\*\//g, '')} */`)
      parts.push(`  ${key}${optional ? '?' : ''}: ${type}`)
    }
    parts.push('}', '')
  }
  return parts.join('\n')
}

// --------------------------------------------------------------- operations

const HTTP_METHODS = ['get', 'post', 'put', 'delete', 'patch']

/**
 * Derive a stable, collision-free key for an operation. The specs declare no
 * operationId, so the key is <method><PathSegments>; `{param}` segments become
 * `ByParam`. These keys are internal — src/resources/* gives them good names.
 */
function operationKey(method, path, version) {
  const segments = path
    .replace(/^\/api\/(v2\/)?publicApi\/?/i, '')
    .split('/')
    .filter(Boolean)
    .map((seg) => {
      const param = seg.match(/^\{(.+)\}$/)
      if (param) return `By${pascal(param[1])}`
      return seg.split(/[-_.]/).filter(Boolean).map(pascal).join('')
    })
  const base = method + segments.join('')
  return version === 'v2' ? `v2${pascal(base)}` : base
}

const DOWNLOAD_RE = /\/(pdf|xml|signature)$|\/ubl\/\{/i

function requestBodyKind(op, version) {
  const content = op.requestBody?.content
  if (!content) return { body: 'none' }
  if (content['multipart/form-data']) {
    const props = content['multipart/form-data'].schema?.properties ?? {}
    return { body: 'multipart', bodyPart: Object.keys(props)[0] ?? 'file' }
  }
  if (content['application/json']) {
    return { body: 'json', bodyType: tsType(content['application/json'].schema, version) }
  }
  const xml = content['application/xml'] ?? content['text/xml']
  if (xml) {
    // A bare `{type: string}` XML body is a raw UBL document; a $ref means a
    // structured payload the server will also accept as JSON.
    if (xml.schema?.$ref) {
      return { body: 'json', bodyType: tsType(xml.schema, version) }
    }
    return { body: 'xml' }
  }
  return { body: 'none' }
}

function responseKind(op, path, version) {
  const content = op.responses?.['200']?.content
  if (!content || Object.keys(content).length === 0) {
    // Undeclared 200. Download routes stream bytes; everything else still
    // returns JSON, it is just missing from the spec.
    return DOWNLOAD_RE.test(path) ? { response: 'binary' } : { response: 'json' }
  }
  const schema =
    content['application/json']?.schema ??
    content['text/plain']?.schema ??
    Object.values(content)[0]?.schema
  if (!schema) return { response: 'json' }
  if (schema.$ref || schema.type === 'array' || schema.type === 'object') {
    return { response: 'json', responseType: tsType(schema, version) }
  }
  if (schema.type === 'string') return { response: 'text' }
  return { response: 'json', responseType: tsType(schema, version) }
}

function collectOperations() {
  const ops = new Map()
  for (const [spec, version] of [
    [v1, 'v1'],
    [v2, 'v2'],
  ]) {
    for (const [path, item] of Object.entries(spec.paths)) {
      for (const method of HTTP_METHODS) {
        const op = item[method]
        if (!op) continue
        const key = operationKey(method, path, version)
        if (ops.has(key)) throw new Error(`duplicate operation key: ${key} (${method} ${path})`)
        const params = op.parameters ?? []
        const query = params.filter((p) => p.in === 'query').map((p) => p.name)
        const pathParams = params.filter((p) => p.in === 'path').map((p) => p.name)
        // Path templates sometimes carry params the parameter list omits.
        for (const m of path.matchAll(/\{(.+?)\}/g)) {
          if (!pathParams.includes(m[1])) pathParams.push(m[1])
        }
        ops.set(key, {
          key,
          version,
          method: method.toUpperCase(),
          path,
          pathParams,
          query,
          summary: op.summary ?? '',
          ...requestBodyKind(op, version),
          ...responseKind(op, path, version),
        })
      }
    }
  }
  return ops
}

const operations = collectOperations()

function emitOperations() {
  const parts = [BANNER]
  parts.push(`export interface OperationDef {
  /** Which SEF API surface this belongs to. */
  readonly version: 'v1' | 'v2'
  readonly method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH'
  /** Path template; \`{name}\` placeholders are filled from pathParams. */
  readonly path: string
  readonly pathParams: readonly string[]
  readonly query: readonly string[]
  /** How the request body is encoded. */
  readonly body: 'json' | 'xml' | 'multipart' | 'none'
  /** Field name for a multipart body. */
  readonly bodyPart?: string
  /** How the 200 response is decoded. */
  readonly response: 'json' | 'text' | 'binary'
  readonly summary: string
}
`)
  parts.push('export const operations = {')
  for (const op of [...operations.values()].sort((a, b) => a.key.localeCompare(b.key))) {
    const fields = [
      `version: ${lit(op.version)}`,
      `method: ${lit(op.method)}`,
      `path: ${lit(op.path)}`,
      `pathParams: [${op.pathParams.map(lit).join(', ')}]`,
      `query: [${op.query.map(lit).join(', ')}]`,
      `body: ${lit(op.body)}`,
      ...(op.bodyPart ? [`bodyPart: ${lit(op.bodyPart)}`] : []),
      `response: ${lit(op.response)}`,
      `summary: ${lit(op.summary)}`,
    ]
    parts.push(`  ${op.key}: {`)
    for (const f of fields) parts.push(`    ${f},`)
    parts.push(`  },`)
  }
  parts.push('} as const satisfies Record<string, OperationDef>', '')
  parts.push('export type OperationKey = keyof typeof operations', '')
  return parts.join('\n')
}

// ------------------------------------------------- generated docs reference

/**
 * The operations table is also published as a documentation page, so the docs
 * cannot drift from the spec. Prose lives in the hand-written pages; this file
 * is data only.
 */
function emitOperationsDoc() {
  const rows = [...operations.values()].sort(
    (a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method),
  )
  const bodyLabel = { json: 'JSON', xml: 'XML', multipart: 'multipart', none: '–' }
  const respLabel = { json: 'JSON', text: 'tekst', binary: 'datoteka' }
  const lines = [
    '<!-- Generisano skriptom scripts/generate.mjs. Ne menjajte ručno. -->',
    '',
    '# Sve operacije',
    '',
    `Tabela je generisana iz zvaničnih OpenAPI dokumenata SEF-a, pa uvek odgovara`,
    `stvarnom stanju API-ja. Ukupno operacija: **${rows.length}**.`,
    '',
    'Ključ iz prve kolone prosleđuje se metodi `sef.http.call()`:',
    '',
    '```ts',
    "await sef.http.call('getPurchaseInvoiceOverview', {",
    "  query: { dateFrom: '2026-08-01', dateTo: '2026-08-31' },",
    '})',
    '```',
    '',
    'Za svakodnevni rad koristite imenovane metode iz prostora imena; ovaj spisak',
    'služi kada vam treba operacija koju one ne izlažu.',
    '',
    '| Ključ | Metoda | Putanja | Telo | Odgovor |',
    '| --- | --- | --- | --- | --- |',
  ]
  for (const op of rows) {
    lines.push(
      `| \`${op.key}\` | ${op.method} | \`${op.path}\` | ${bodyLabel[op.body]} | ${respLabel[op.response]} |`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

// -------------------------------------------------------------------- write

const outDir = new URL('src/generated/', root)
mkdirSync(outDir, { recursive: true })
writeFileSync(new URL('enums.ts', outDir), emitEnums())
writeFileSync(new URL('types.ts', outDir), emitTypes())
writeFileSync(new URL('operations.ts', outDir), emitOperations())
writeFileSync(new URL('docs/api/operacije.md', root), emitOperationsDoc())

const byVersion = { v1: 0, v2: 0 }
for (const op of operations.values()) byVersion[op.version]++
console.log(`enums.ts      ${enumEntries.length} enums`)
console.log(`types.ts      ${[...schemas.values()].filter((s) => !s.schema.enum).length} interfaces`)
console.log(`operations.ts ${operations.size} operations (v1: ${byVersion.v1}, v2: ${byVersion.v2})`)
console.log(`operacije.md  ${operations.size} rows -> docs/api/operacije.md`)
